const express = require('express');
const router = express.Router();
const { emaCacheMiddleware } = require('../middleware/emaCache');

const authRoutes = require('./auth');
const adminRoutes = require('./admin');
const catalogRoutes = require('./catalog');
const contentRoutes = require('./content');
const commerceRoutes = require('./commerce');
const paymentRoutes = require('./payment');
const shiprocketRoutes = require('./shiprocket');
const supportRoutes = require('./support');
const storyRoutes = require('./story');
const homePosterRoutes = require('./homePoster');
const sliderRoutes = require('./slider');
const aboutUsRoutes = require('./aboutUs');
const contactPageRoutes = require('./contactPage');
const storeLocatorRoutes = require('./storeLocator');
const privacyPolicyRoutes = require('./privacyPolicy');
const shippingPolicyRoutes = require('./shippingPolicy');
const termAndConditionRoutes = require('./termAndCondition');
const returnPolicyRoutes = require('./returnPolicy');
const cartRoutes = require('./cart');
const wishlistRoutes = require('./wishlist');
const countryRoutes = require('./country');
const addressRoutes = require('./address');
const dashboardRoutes = require('./dashboard');
const reportsRoutes = require('./reports');
const shippingRoutes = require('./shipping');

router.use('/auth', authRoutes);
router.use('/admin', adminRoutes);
router.use('/catalog', emaCacheMiddleware, catalogRoutes);
router.use('/content', contentRoutes);
router.use('/commerce', commerceRoutes);
router.use('/payment', paymentRoutes);
router.use('/shiprocket', shiprocketRoutes);
router.use('/support', supportRoutes);
router.use('/story', storyRoutes);
router.use('/home-poster', homePosterRoutes);
router.use('/slider', sliderRoutes);
router.use('/about-us', aboutUsRoutes);
router.use('/contact-page', contactPageRoutes);
router.use('/store-locator', storeLocatorRoutes);
router.use('/privacy-policy', privacyPolicyRoutes);
router.use('/shipping-policy', shippingPolicyRoutes);
router.use('/terms-conditions', termAndConditionRoutes);
router.use('/return-policy', returnPolicyRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/country', countryRoutes);
router.use('/address', addressRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportsRoutes);
router.use('/shipping', shippingRoutes);

module.exports = router;